### ISSUE TITLE
feat: Support ABI URL

### ISSUE THREAD

**Issue by enzofoucaud** [SkullElf/ABI2API#6]
It would be nice to support ABI URL like [https://farmtrees.etrees.green/elrondtreesgame.abi.json](https://farmtrees.etrees.green/elrondtreesgame.abi.json)

**Comment by SkullElf** [comment]
Support in remote ABI JSON added in:
https://github.com/SkullElf/ABI2API/pull/7

Thank you for your contribution 💪
